name: CI

on:
  push:
    branches:
      - dev

env:
  GUM_OPTIONS: '--enable-gumpp --enable-gumjs --with-devkits=gum,gumjs --enable-tests'

jobs:
  

  native:
    # strategy:
    #   matrix:
    #     include:
    #       - { id: windows-x86,    runner: '"windows-latest"'                    }
    #   fail-fast: false
    runs-on: [self-hosted, windows-x86]  # Matches your runner's label
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Build
        run: |
          .\configure --host=x86 ${{ env.GUM_OPTIONS }}
          .\make
    
      - name: Upload Gum devkit
        uses: actions/upload-artifact@v4
        with:
          name: gum-devkit
          path: build/gum/devkit/
      - name: Upload GumJS devkit
        uses: actions/upload-artifact@v4
        with:
          name: gumjs-devkit
          path: build/bindings/gumjs/devkit/
